### ISSUE TITLE
Symlinks in modules are depricated

### ISSUE THREAD

**Issue by tjcwilk** [jhaals/jhaals-osx_notify#2]
When the module is installed from the puppet forge, the following warning message comes up:

> puppet module install jhaals-osx_notify
> 
> Warning: Symlinks in modules are unsupported. Please investigate symlink jhaals-osx_notify-0.0.4/spec/fixtures/modules/osx_notify/lib->../../../../lib.
> 
> Warning: Symlinks in modules are unsupported. Please investigate symlink jhaals-osx_notify-0.0.4/spec/fixtures/modules/osx_notify/manifests->../../../../manifests.

**Comment by jhaals** [comment]
I don't maintain this module anymore. I would gladly accept PR's if you'd like to fix this issue.
