### ISSUE TITLE
US-ASCII \xC3

### ISSUE THREAD

**Issue by tjcwilk** [jhaals/jhaals-osx_notify#3]
After installing the module from the puppet forge, and then immediatly running a puppet agent --test, the modules does not get pushed down and used correctly. The following errors occur:

> Info: Retrieving pluginfacts
> 
> Error: /File[/var/lib/puppet/facts.d]: Failed to generate additional resources using 'eval_generate': Error 400 on SERVER: "\xC3" on US-ASCII
> 
> Error: /File[/var/lib/puppet/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet://puppet/pluginfacts: Error 400 on SERVER: "\xC3" on US-ASCII

**Comment by jhaals** [comment]
I'm sorry but this module is no longer under development
